### ISSUE TITLE
spinnaker_python-3.1.0.79-cp310-cp310-linux_x86_64 breaks Simple_pyspin

### ISSUE THREAD

**Issue by MaximilianHoffmann** [MaimonLab/flir_camera_driver#2]
`img_cv, chunk_data = cam.get_array(get_chunk=True)`
`chunk_data.GetTimestamp()`
`Segmentation fault (core dumped)`

I still am not exactly sure what's going on, so it's for now a note to myself.  On option is a re-write without simple_pyspin , which is stale.

**Comment by jdryu** [comment]
Simple_Pyspin should no longer be an issue.
